##                                      Leitura do código

In [ ]:
from datetime import datetime
import pandas as pd

# sep=r'\s+' para tabulações
df = pd.read_csv('LCPA.csv', sep=r'\t')

df.head()

C:\Users\daniel-pc\AppData\Local\Temp\ipykernel_24164\2134988412.py:5: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df = pd.read_csv('marketing_campaign.csv', sep=r'\t')

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [3]:
df.shape

(2240, 29)

## Mapeamento do csv

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   str
 3   Marital_Status       2240 non-null   str
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   str
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), str(3)
memory usage: 561.4 KB

#### Mapeamento de nulos

In [5]:
df.isnull().sum()

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

#### Mapeamento de duplicatas

In [6]:
df.duplicated().sum()

np.int64(0)

#### Identificação de anomalias na coluna idade

In [7]:
df['Year_Birth'].describe()

count    2240.000000
mean     1968.805804
std        11.984069
min      1893.000000
25%      1959.000000
50%      1970.000000
75%      1977.000000
max      1996.000000
Name: Year_Birth, dtype: float64

### Tratamento dos Dados

#### Remove pessoas com data de nascimento menor que 1940

In [8]:
df = df[df['Year_Birth'] >= 1940]
df[df['Year_Birth'] < 1940]['Year_Birth'].head(50) #Teste

Series([], Name: Year_Birth, dtype: int64)

#### Tratamento de nulos da coluna "renda"(Income)

In [9]:
mediana_renda = df['Income'].median()
df['Income'] = df['Income'].fillna(mediana_renda)
df['Income'].isna().sum()

np.int64(0)

#### Tratamento da coluna "estado civil" (Marital_Status)

##### Averiguação de valores distintos

In [10]:
df['Marital_Status'].unique()

<ArrowStringArray>
['Single', 'Together', 'Married', 'Divorced', 'Widow', 'Alone', 'Absurd',
 'YOLO']
Length: 8, dtype: str

In [11]:
estado_civil_dic = {
    'Alone': 'Single',
    'YOLO': 'Single',
    'Absurd': 'Single'
}

df['Marital_Status'] = df['Marital_Status'].replace(estado_civil_dic)

df['Marital_Status'].unique()

<ArrowStringArray>
['Single', 'Together', 'Married', 'Divorced', 'Widow']
Length: 5, dtype: str

##### Transformação de data (string) para data real

In [12]:
df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'], dayfirst=True)

#### Engenharia de Atributos (Gerar valor para análises)

##### Criação de coluna idade

In [13]:
df['Idade'] = datetime.now().year - df['Year_Birth']
df['Idade'].head(50)

0     69
1     72
2     61
3     42
4     45
5     59
6     55
7     41
8     52
9     76
10    43
11    50
12    67
13    74
14    39
15    80
16    46
17    80
18    77
19    41
20    44
21    47
22    77
23    72
24    75
25    57
26    50
27    40
28    37
29    61
30    37
31    63
32    56
33    74
34    80
35    75
36    56
37    50
38    53
39    83
40    46
41    41
42    69
43    67
44    51
45    50
46    30
47    58
48    75
49    72
Name: Idade, dtype: int64

##### Criação da coluna "Gastos Totais"

In [14]:
df['Gasto_Total'] = df['MntWines'] + df['MntFruits'] + df['MntMeatProducts'] + df['MntFishProducts'] + df['MntSweetProducts']
df['Gasto_Total'].head()

0    1529
1      21
2     734
3      48
4     407
Name: Gasto_Total, dtype: int64

##### Criação da coluna "Total_Filhos"

In [15]:
df['Total_Filhos'] = df['Kidhome'] + df['Teenhome']
df['Total_Filhos'].head()

0    0
1    2
2    0
3    1
4    1
Name: Total_Filhos, dtype: int64

##### Criação da coluna "Anos_De_Loja"

In [16]:
df['Anos_De_Loja'] = datetime.now().year - df['Dt_Customer'].dt.year
df.columns

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome',
       'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits',
       'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response',
       'Idade', 'Gasto_Total', 'Total_Filhos', 'Anos_De_Loja'],
      dtype='str')

##### Drop de colunas inuteis

In [17]:
df = df.drop(columns=['Year_Birth', 'Kidhome', 'Teenhome'], errors='ignore')
df.head(50)

,ID,Education,Marital_Status,Income,Dt_Customer,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,...,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Idade,Gasto_Total,Total_Filhos,Anos_De_Loja
0,5524,Graduation,Single,58138.0,2012-09-04,58,635,88,546,172,...,0,0,0,3,11,1,69,1529,0,14
1,2174,Graduation,Single,46344.0,2014-03-08,38,11,1,6,2,...,0,0,0,3,11,0,72,21,2,12
2,4141,Graduation,Together,71613.0,2013-08-21,26,426,49,127,111,...,0,0,0,3,11,0,61,734,0,13
3,6182,Graduation,Together,26646.0,2014-02-10,26,11,4,20,10,...,0,0,0,3,11,0,42,48,1,12
4,5324,PhD,Married,58293.0,2014-01-19,94,173,43,118,46,...,0,0,0,3,11,0,45,407,1,12
5,7446,Master,Together,62513.0,2013-09-09,16,520,42,98,0,...,0,0,0,3,11,0,59,702,1,13
6,965,Graduation,Divorced,55635.0,2012-11-13,34,235,65,164,50,...,0,0,0,3,11,0,55,563,1,14
7,6177,PhD,Married,33454.0,2013-05-08,32,76,10,56,3,...,0,0,0,3,11,0,41,146,1,13
8,4855,PhD,Together,30351.0,2013-06-06,19,14,0,24,3,...,0,0,0,3,11,1,52,44,1,13
9,5899,PhD,Together,5648.0,2014-03-13,68,28,0,6,1,...,0,0,0,3,11,0,76,36,2,12
10,1994,Graduation,Married,51373.0,2013-11-15,11,5,5,6,0,...,0,0,0,3,11,0,43,18,1,13
11,387,Basic,Married,7500.0,2012-11-13,59,6,16,11,11,...,0,0,0,3,11,0,50,45,0,14
12,2125,Graduation,Divorced,63033.0,2013-11-15,82,194,61,480,225,...,0,0,0,3,11,0,67,1072,0,13
13,8180,Master,Divorced,59354.0,2013-11-15,53,233,2,53,3,...,0,0,0,3,11,0,74,296,2,13
14,2569,Graduation,Married,17323.0,2012-10-10,38,3,14,17,6,...,0,0,0,3,11,0,39,41,0,14
15,2114,PhD,Single,82800.0,2012-11-24,23,1006,22,115,59,...,1,0,0,3,11,1,80,1270,0,14
16,9736,Graduation,Married,41850.0,2012-12-24,51,53,5,19,2,...,0,0,0,3,11,0,46,92,2,14
17,4939,Graduation,Together,37760.0,2012-08-31,20,84,5,38,150,...,0,0,0,3,11,0,80,289,0,14
18,6565,Master,Married,76995.0,2013-03-28,91,1012,80,498,0,...,1,0,0,3,11,0,77,1606,1,13
19,2278,2n Cycle,Single,33812.0,2012-11-03,86,4,17,19,30,...,0,0,0,3,11,0,41,94,1,14
20,9360,Graduation,Married,37040.0,2012-08-08,41,86,2,73,69,...,0,0,0,3,11,0,44,268,0,14
21,5376,Graduation,Married,2447.0,2013-01-06,42,1,1,1725,1,...,0,0,0,3,11,0,47,1729,1,13
22,1993,PhD,Married,58607.0,2012-12-23,63,867,0,86,0,...,0,0,0,3,11,0,77,953,1,14
23,4047,PhD,Married,65324.0,2014-01-11,0,384,0,102,21,...,0,0,0,3,11,0,72,539,1,12
24,1409,Graduation,Together,40689.0,2013-03-18,69,270,3,27,39,...,0,0,0,3,11,0,75,345,1,13
25,7892,Graduation,Single,18589.0,2013-01-02,89,6,4,25,15,...,0,0,0,3,11,0,57,62,0,13
26,2404,Graduation,Married,53359.0,2013-05-27,4,173,4,30,3,...,0,0,0,3,11,0,50,216,2,13
27,5255,Graduation,Single,51373.0,2013-02-20,19,5,1,3,3,...,0,0,0,3,11,0,40,275,1,13
28,9422,Graduation,Married,38360.0,2013-05-31,26,36,2,42,20,...,0,0,0,3,11,0,37,121,1,13
29,1966,PhD,Married,84618.0,2013-11-22,96,684,100,801,21,...,0,0,0,3,11,0,61,1672,0,13
30,6864,Master,Divorced,10979.0,2014-05-22,34,8,4,10,2,...,0,0,0,3,11,0,37,26,0,12
31,3033,Master,Together,38620.0,2013-05-11,56,112,17,44,34,...,0,0,0,3,11,0,63,229,0,13
32,5710,Graduation,Together,40548.0,2012-10-10,31,110,0,5,2,...,0,0,0,3,11,0,56,117,1,14
33,7373,PhD,Divorced,46610.0,2012-10-29,8,96,12,96,33,...,0,0,0,3,11,1,74,259,2,14
34,8755,Master,Married,68657.0,2013-02-20,4,482,34,471,119,...,0,0,0,3,11,0,80,1174,0,13
35,10738,Master,Single,49389.0,2013-08-29,55,40,0,19,2,...,0,0,0,3,11,0,75,62,2,13
36,4339,PhD,Married,67353.0,2013-12-31,37,702,17,151,0,...,0,0,0,3,11,0,56,878,1,13
37,10755,2n Cycle,Married,23718.0,2013-09-02,76,6,3,14,15,...,0,0,0,3,11,0,50,45,1,13
38,8595,Graduation,Widow,42429.0,2014-02-11,99,55,0,6,2,...,0,0,0,3,11,0,53,63,1,12
39,2968,PhD,Divorced,48948.0,2013-02-01,53,437,8,206,160,...,0,0,0,3,11,1,83,860,0,13
40,8601,Graduation,Married,80011.0,2013-04-29,3,421,76,536,82,...,0,0,0,3,11,0,46,1293,1,13
41,503,Master,Married,20559.0,2013-03-12,88,13,1,29,3,...,0,0,0,3,11,0,41,46,1,13
42,8430,Graduation,Together,21994.0,2012-12-24,4,9,0,6,3,...,0,0,0,3,11,0,69,19,1,14
43,7281,PhD,Single,51373.0,2013-11-05,80,81,11,50,3,...,0,0,0,3,11,0,67,147,0,13
44,2139,Master,Married,7500.0,2013-10-02,19,3,1,10,3,...,0,0,0,3,11,0,51,19,1,13
45,1371,Graduation,Single,79941.0,2014-06-28,72,123,164,266,227,...,0,0,0,3,11,0,50,810,0,12
46,9909,2n Cycle,Married,7500.0,2012-11-09,24,3,18,14,15,...,0,0,0,3,11,1,30,72,0,14
47,7286,Graduation,Together,41728.0,2013-05-24,92,13,6,15,3,...,0,0,0,3,11,0,58,42,1,13
48,7244,Graduation,Single,51373.0,2014-01-01,96,48,5,48,6,...,0,0,0,3,11,0,75,117,3,12
49,6566,PhD,Married,72550.0,2012-11-08,39,826,50,317,50,...,0,0,0,3,11,0,72,1281,2,14

In [ ]:
df.to_csv('limpo_LCPA.csv', index=False)